SRCDIR = .
BINDIR = ../bin
LIBDIR = ../lib
OBJDIR = .
CC=gcc -g 
CXX=g++ -g 
LD=gcc 
CXXFLAGS = 
CFLAGS = 
RM = rm -f
MV = mv 
CP = cp 
MAKE = make
SRC = $(wildcard ./*.cpp)
CPPFLAGS = -I. -I./CCfits
LIBS = 
LDFLAGS = -lm
EEXT=
OEXT=.o
AR=ar rcs
TARGET0 = agilefilename
OTARGET0 = ./agilefilename.o
TARGET1 = agiletimer
OTARGET1 = ./agiletimer.o
TARGET2 = archivemodule
OTARGET2 = ./archivemodule.o
TARGET3 = commandlineexception
OTARGET3 = ./commandlineexception.o
TARGET4 = connector
OTARGET4 = ./connector.o
TARGET5 = emptyfilenameexception
OTARGET5 = ./emptyfilenameexception.o
TARGET6 = event
OTARGET6 = ./event.o
TARGET7 = eventlist
OTARGET7 = ./eventlist.o
TARGET8 = existingfileexception
OTARGET8 = ./existingfileexception.o
TARGET9 = filecompressedexception
OTARGET9 = ./filecompressedexception.o
TARGET10 = filelist
OTARGET10 = ./filelist.o
TARGET11 = filenotpresentexception
OTARGET11 = ./filenotpresentexception.o
TARGET12 = fitsfile
OTARGET12 = ./fitsfile.o
TARGET13 = gnuplot_base
OTARGET13 = ./gnuplot_base.o
TARGET14 = gnuplot_pipe
OTARGET14 = ./gnuplot_pipe.o
TARGET15 = gnuplot_tmpfile
OTARGET15 = ./gnuplot_tmpfile.o
TARGET16 = hertagbase
OTARGET16 = ./hertagbase.o
TARGET17 = irospointpilot
OTARGET17 = ./irospointpilot.o
TARGET18 = l1_9eventlist
OTARGET18 = ./l1_9eventlist.o
TARGET19 = l2photonlist
OTARGET19 = ./l2photonlist.o
TARGET20 = l3photonlist
OTARGET20 = ./l3photonlist.o
TARGET21 = mdimage
OTARGET21 = ./mdimage.o
TARGET22 = nonstandardfileexception
OTARGET22 = ./nonstandardfileexception.o
TARGET23 = outputfileexception
OTARGET23 = ./outputfileexception.o
TARGET24 = processkiller
OTARGET24 = ./processkiller.o
TARGET25 = sadataset
OTARGET25 = ./sadataset.o
TARGET26 = sadatetime
OTARGET26 = ./sadatetime.o
TARGET27 = saevent
OTARGET27 = ./saevent.o
TARGET28 = saexception
OTARGET28 = ./saexception.o
TARGET29 = safilenamer
OTARGET29 = ./safilenamer.o
TARGET30 = sal3event
OTARGET30 = ./sal3event.o
TARGET31 = sametadata
OTARGET31 = ./sametadata.o
TARGET32 = samonitor
OTARGET32 = ./samonitor.o
TARGET33 = sanominalpointing
OTARGET33 = ./sanominalpointing.o
TARGET34 = saparameter
OTARGET34 = ./saparameter.o
TARGET35 = saplot
OTARGET35 = ./saplot.o
TARGET36 = sasoacommand
OTARGET36 = ./sasoacommand.o
TARGET37 = sasoacommandlist
OTARGET37 = ./sasoacommandlist.o
TARGET38 = sasoalog
OTARGET38 = ./sasoalog.o
TARGET39 = systemconnector
OTARGET39 = ./systemconnector.o
TARGET40 = timer
OTARGET40 = ./timer.o
TARGET41 = type1exception
OTARGET41 = ./type1exception.o
TARGET42 = type2exception
OTARGET42 = ./type2exception.o
TARGETS = type2exception type1exception timer systemconnector sasoalog sasoacommandlist sasoacommand saplot saparameter sanominalpointing samonitor sametadata sal3event safilenamer saexception saevent sadatetime sadataset processkiller outputfileexception nonstandardfileexception mdimage l3photonlist l2photonlist l1_9eventlist irospointpilot hertagbase gnuplot_tmpfile gnuplot_pipe gnuplot_base fitsfile filenotpresentexception filelist filecompressedexception existingfileexception eventlist event emptyfilenameexception connector commandlineexception archivemodule agiletimer agilefilename
RMTARGETS = ./type2exception ./type1exception ./timer ./systemconnector ./sasoalog ./sasoacommandlist ./sasoacommand ./saplot ./saparameter ./sanominalpointing ./samonitor ./sametadata ./sal3event ./safilenamer ./saexception ./saevent ./sadatetime ./sadataset ./processkiller ./outputfileexception ./nonstandardfileexception ./mdimage ./l3photonlist ./l2photonlist ./l1_9eventlist ./irospointpilot ./hertagbase ./gnuplot_tmpfile ./gnuplot_pipe ./gnuplot_base ./fitsfile ./filenotpresentexception ./filelist ./filecompressedexception ./existingfileexception ./eventlist ./event ./emptyfilenameexception ./connector ./commandlineexception ./archivemodule ./agiletimer ./agilefilename
OTARGETS = ./type2exception.o ./type1exception.o ./timer.o ./systemconnector.o ./sasoalog.o ./sasoacommandlist.o ./sasoacommand.o ./saplot.o ./saparameter.o ./sanominalpointing.o ./samonitor.o ./sametadata.o ./sal3event.o ./safilenamer.o ./saexception.o ./saevent.o ./sadatetime.o ./sadataset.o ./processkiller.o ./outputfileexception.o ./nonstandardfileexception.o ./mdimage.o ./l3photonlist.o ./l2photonlist.o ./l1_9eventlist.o ./irospointpilot.o ./hertagbase.o ./gnuplot_tmpfile.o ./gnuplot_pipe.o ./gnuplot_base.o ./fitsfile.o ./filenotpresentexception.o ./filelist.o ./filecompressedexception.o ./existingfileexception.o ./eventlist.o ./event.o ./emptyfilenameexception.o ./connector.o ./commandlineexception.o ./archivemodule.o ./agiletimer.o ./agilefilename.o
OBJ = $(OTARGETS)
all: $(OBJ) libsas.a
$(SRCDIR)/$(TARGET0)$(OEXT): $(SRCDIR)/$(TARGET0).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET0).cpp  -o $(SRCDIR)/agilefilename.o
$(SRCDIR)/$(TARGET1)$(OEXT): $(SRCDIR)/$(TARGET1).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET1).cpp  -o $(SRCDIR)/agiletimer.o
$(SRCDIR)/$(TARGET2)$(OEXT): $(SRCDIR)/$(TARGET2).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET2).cpp  -o $(SRCDIR)/archivemodule.o
$(SRCDIR)/$(TARGET3)$(OEXT): $(SRCDIR)/$(TARGET3).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET3).cpp  -o $(SRCDIR)/commandlineexception.o
$(SRCDIR)/$(TARGET4)$(OEXT): $(SRCDIR)/$(TARGET4).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET4).cpp  -o $(SRCDIR)/connector.o
$(SRCDIR)/$(TARGET5)$(OEXT): $(SRCDIR)/$(TARGET5).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET5).cpp  -o $(SRCDIR)/emptyfilenameexception.o
$(SRCDIR)/$(TARGET6)$(OEXT): $(SRCDIR)/$(TARGET6).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET6).cpp  -o $(SRCDIR)/event.o
$(SRCDIR)/$(TARGET7)$(OEXT): $(SRCDIR)/$(TARGET7).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET7).cpp  -o $(SRCDIR)/eventlist.o
$(SRCDIR)/$(TARGET8)$(OEXT): $(SRCDIR)/$(TARGET8).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET8).cpp  -o $(SRCDIR)/existingfileexception.o
$(SRCDIR)/$(TARGET9)$(OEXT): $(SRCDIR)/$(TARGET9).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET9).cpp  -o $(SRCDIR)/filecompressedexception.o
$(SRCDIR)/$(TARGET10)$(OEXT): $(SRCDIR)/$(TARGET10).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET10).cpp  -o $(SRCDIR)/filelist.o
$(SRCDIR)/$(TARGET11)$(OEXT): $(SRCDIR)/$(TARGET11).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET11).cpp  -o $(SRCDIR)/filenotpresentexception.o
$(SRCDIR)/$(TARGET12)$(OEXT): $(SRCDIR)/$(TARGET12).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET12).cpp  -o $(SRCDIR)/fitsfile.o
$(SRCDIR)/$(TARGET13)$(OEXT): $(SRCDIR)/$(TARGET13).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET13).cpp  -o $(SRCDIR)/gnuplot_base.o
$(SRCDIR)/$(TARGET14)$(OEXT): $(SRCDIR)/$(TARGET14).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET14).cpp  -o $(SRCDIR)/gnuplot_pipe.o
$(SRCDIR)/$(TARGET15)$(OEXT): $(SRCDIR)/$(TARGET15).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET15).cpp  -o $(SRCDIR)/gnuplot_tmpfile.o
$(SRCDIR)/$(TARGET16)$(OEXT): $(SRCDIR)/$(TARGET16).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET16).cpp  -o $(SRCDIR)/hertagbase.o
$(SRCDIR)/$(TARGET17)$(OEXT): $(SRCDIR)/$(TARGET17).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET17).cpp  -o $(SRCDIR)/irospointpilot.o
$(SRCDIR)/$(TARGET18)$(OEXT): $(SRCDIR)/$(TARGET18).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET18).cpp  -o $(SRCDIR)/l1_9eventlist.o
$(SRCDIR)/$(TARGET19)$(OEXT): $(SRCDIR)/$(TARGET19).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET19).cpp  -o $(SRCDIR)/l2photonlist.o
$(SRCDIR)/$(TARGET20)$(OEXT): $(SRCDIR)/$(TARGET20).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET20).cpp  -o $(SRCDIR)/l3photonlist.o
$(SRCDIR)/$(TARGET21)$(OEXT): $(SRCDIR)/$(TARGET21).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET21).cpp  -o $(SRCDIR)/mdimage.o
$(SRCDIR)/$(TARGET22)$(OEXT): $(SRCDIR)/$(TARGET22).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET22).cpp  -o $(SRCDIR)/nonstandardfileexception.o
$(SRCDIR)/$(TARGET23)$(OEXT): $(SRCDIR)/$(TARGET23).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET23).cpp  -o $(SRCDIR)/outputfileexception.o
$(SRCDIR)/$(TARGET24)$(OEXT): $(SRCDIR)/$(TARGET24).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET24).cpp  -o $(SRCDIR)/processkiller.o
$(SRCDIR)/$(TARGET25)$(OEXT): $(SRCDIR)/$(TARGET25).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET25).cpp  -o $(SRCDIR)/sadataset.o
$(SRCDIR)/$(TARGET26)$(OEXT): $(SRCDIR)/$(TARGET26).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET26).cpp  -o $(SRCDIR)/sadatetime.o
$(SRCDIR)/$(TARGET27)$(OEXT): $(SRCDIR)/$(TARGET27).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET27).cpp  -o $(SRCDIR)/saevent.o
$(SRCDIR)/$(TARGET28)$(OEXT): $(SRCDIR)/$(TARGET28).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET28).cpp  -o $(SRCDIR)/saexception.o
$(SRCDIR)/$(TARGET29)$(OEXT): $(SRCDIR)/$(TARGET29).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET29).cpp  -o $(SRCDIR)/safilenamer.o
$(SRCDIR)/$(TARGET30)$(OEXT): $(SRCDIR)/$(TARGET30).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET30).cpp  -o $(SRCDIR)/sal3event.o
$(SRCDIR)/$(TARGET31)$(OEXT): $(SRCDIR)/$(TARGET31).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET31).cpp  -o $(SRCDIR)/sametadata.o
$(SRCDIR)/$(TARGET32)$(OEXT): $(SRCDIR)/$(TARGET32).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET32).cpp  -o $(SRCDIR)/samonitor.o
$(SRCDIR)/$(TARGET33)$(OEXT): $(SRCDIR)/$(TARGET33).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET33).cpp  -o $(SRCDIR)/sanominalpointing.o
$(SRCDIR)/$(TARGET34)$(OEXT): $(SRCDIR)/$(TARGET34).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET34).cpp  -o $(SRCDIR)/saparameter.o
$(SRCDIR)/$(TARGET35)$(OEXT): $(SRCDIR)/$(TARGET35).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET35).cpp  -o $(SRCDIR)/saplot.o
$(SRCDIR)/$(TARGET36)$(OEXT): $(SRCDIR)/$(TARGET36).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET36).cpp  -o $(SRCDIR)/sasoacommand.o
$(SRCDIR)/$(TARGET37)$(OEXT): $(SRCDIR)/$(TARGET37).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET37).cpp  -o $(SRCDIR)/sasoacommandlist.o
$(SRCDIR)/$(TARGET38)$(OEXT): $(SRCDIR)/$(TARGET38).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET38).cpp  -o $(SRCDIR)/sasoalog.o
$(SRCDIR)/$(TARGET39)$(OEXT): $(SRCDIR)/$(TARGET39).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET39).cpp  -o $(SRCDIR)/systemconnector.o
$(SRCDIR)/$(TARGET40)$(OEXT): $(SRCDIR)/$(TARGET40).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET40).cpp  -o $(SRCDIR)/timer.o
$(SRCDIR)/$(TARGET41)$(OEXT): $(SRCDIR)/$(TARGET41).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET41).cpp  -o $(SRCDIR)/type1exception.o
$(SRCDIR)/$(TARGET42)$(OEXT): $(SRCDIR)/$(TARGET42).cpp
	$(CXX) $(CPPFLAGS) -c $(SRCDIR)/$(TARGET42).cpp  -o $(SRCDIR)/type2exception.o
libsas.a: $(OBJ)
	 $(AR) libsas.a $?
install: all
	 $(MV) libsas.a $(LIBDIR)
.PHONY: clean distclean 
clean: 
	 $(RM) $(OBJ) libsas.a
distclean: clean
	  $(RM) $(BINDIR)/* Makefile* *.fit *.fits *.csv *.ssv *.tsv *.dat *.txt *.log
